#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Drwcli\App;

$app = new App([
    'theme' => 'regular',
    'app_path' => __DIR__ . '/pattern/Command'
]);

$app->runCommand($argv);
